update README.md
paultyng/go-newrelic pull request #65
Opened 2019-10-30 20:40 UTC by ctrombley

Add some additional info to the README.

2019-10-30 20:51 UTC, jthurman42 requested changes

2019-10-30 20:51 UTC, jthurman42 commented on README.md
> +[MIT](https://choosealicense.com/licenses/mit/)
License file in this repo is Apache 2.0, not MIT.  Should link to the file in the repo.

2019-10-30 20:59 UTC, sanderblue requested changes

2019-10-30 20:59 UTC, sanderblue commented on README.md
> +	apps, err := client.ListApplications()
Should we update the indention here to make easier to copy and paste? 😎

2019-10-30 20:59 UTC, sanderblue commented on README.md
> +1. Open a Pull Request
Even though markdown orders this correctly, this kind of confuses me as a reviewer. Not necessarily a blocker, but would it better to use the correct numbers in the markdown or format the numbered list in a different way?

2019-10-30 22:35 UTC, sanderblue submitted a review, later dismissed

2019-10-31 17:09 UTC, jthurman42 submitted a review, later dismissed

2019-10-31 17:09 UTC, jthurman42 commented on README.md
> +[Apache-2.0](https://github.com/paultyng/go-newrelic/blob/master/LICENSE)
This should be a local ref, not the HTTP path

2019-10-31 17:18 UTC, jthurman42 approved these changes

2019-10-31 17:34 UTC, merged