Update make, lots of linting
paultyng/go-newrelic pull request #77
Opened 2019-11-15 23:04 UTC by jthurman42

Update to a more verbose linting and make config.

Big-ish changes:
* Moved the `cmd` package into `internal/cmd`
* Move `main.go` to `cmd/go-newrelic` (result is binary now compiled into `bin/<os>/go-newrelic`

Most other changes are linting related.  Lots of error checking on `w.Write()` (Should refactor these tests at a future date)

The `api` package has not been moved, so this *should* be backwards compatible with external users or the library, unless they are wrapping `cmd` which would seem like an odd thing to do.

Due to that, we *might* want to consider this a for a `5.0.0` release, and if so I'd argue for some more refactoring first (breaking out `api` into domain specific packages, moving under `pkg`, a bigger conversation to have)

Alternatively, we can rollback the move of `cmd` package and change the Makefile to deal with it.

Makefile enhancements:
* Run unit and Integration tests
* Auto-generate documentation
* Use golangci-lint for stricter linting
* Easier cross-compile, directory structure for building multiple platforms
* Travis config updated as well with ci specific make commands

2019-11-18 18:24 UTC, sanderblue commented on Makefile
> +LDFLAGS='-X main.Version=$(PROJECT_VER)'
Nice

2019-11-18 18:25 UTC, sanderblue commented on Makefile
> +include build/document.mk
👍 on breaking these out into individual files

2019-11-19 17:41 UTC, ctrombley requested changes

2019-11-19 17:41 UTC, ctrombley commented on go.mod
> +	github.com/spf13/pflag v1.0.5 // indirect
The `tools-update` target is installing some test dependencies that end up introducing all these indirect references..  If I remember correctly, these caused us some merge issues early on.  

If I delete all the refs in `go.mod` after running `make` and then run a `go mod tidy`, they go away.  Is there a good way to automatically do this after the test run?

2019-11-19 17:41 UTC, ctrombley commented on build/testing.mk
> +test-only: test-unit test-integration
Can we add a line in the development section of the readme that show how to tag tests as unit or integration?

2019-12-09 17:18 UTC, closed without merging

2019-12-09 17:18 UTC, jthurman42 commented
This needs some serious rebase work, will reopen at another time.